/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(crc16_bb.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(ac2bcaae058ac87ae1fe2118b484a27d)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dab/crc16_bb.h>
// pydoc.h is automatically generated in the build directory
#include <crc16_bb_pydoc.h>

void bind_crc16_bb(py::module& m)
{

    using crc16_bb = ::gr::dab::crc16_bb;


    py::class_<crc16_bb, gr::block, gr::basic_block, std::shared_ptr<crc16_bb>>(
        m, "crc16_bb", D(crc16_bb))

        .def(py::init(&crc16_bb::make),
             py::arg("length"),
             py::arg("generator"),
             py::arg("initial_state"),
             D(crc16_bb, make))


        ;
}
