/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(ofdm_move_and_insert_zero.h) */
/* BINDTOOL_HEADER_FILE_HASH(3905d52f56589ebab6234a92cc50e9ad)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dab/ofdm_move_and_insert_zero.h>
// pydoc.h is automatically generated in the build directory
#include <ofdm_move_and_insert_zero_pydoc.h>

void bind_ofdm_move_and_insert_zero(py::module& m)
{

    using ofdm_move_and_insert_zero = ::gr::dab::ofdm_move_and_insert_zero;


    py::class_<ofdm_move_and_insert_zero,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<ofdm_move_and_insert_zero>>(
        m, "ofdm_move_and_insert_zero", D(ofdm_move_and_insert_zero))

        .def(py::init(&ofdm_move_and_insert_zero::make),
             py::arg("fft_length"),
             py::arg("num_carriers"),
             D(ofdm_move_and_insert_zero, make))


        ;
}
