/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(ofdm_insert_pilot_vcc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(58bdf69870b4f2ef1bf993a4609a3350)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dab/ofdm_insert_pilot_vcc.h>
// pydoc.h is automatically generated in the build directory
#include <ofdm_insert_pilot_vcc_pydoc.h>

void bind_ofdm_insert_pilot_vcc(py::module& m)
{

    using ofdm_insert_pilot_vcc = ::gr::dab::ofdm_insert_pilot_vcc;


    py::class_<ofdm_insert_pilot_vcc,
               gr::block,
               gr::basic_block,
               std::shared_ptr<ofdm_insert_pilot_vcc>>(
        m, "ofdm_insert_pilot_vcc", D(ofdm_insert_pilot_vcc))

        .def(py::init(&ofdm_insert_pilot_vcc::make),
             py::arg("pilot"),
             D(ofdm_insert_pilot_vcc, make))


        ;
}
